[[redirects]]
  from = "/tags/"
  to = "/tag-list/"
  status = 200
  force = true 


[[redirects]]
  from = "/tag-list/"
  to = "/tags/"
  status = 301
  force = true 
  

[functions]
  included_files = ["static/cv.html"]